// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: comments.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO COMMENTS(
    id, post_id, user_id, content
) VALUES(
    $1, $2, $3, $4
) RETURNING id, post_id, user_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	ID      string
	PostID  string
	UserID  string
	Content string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.PostID,
		arg.UserID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCommentsByPost = `-- name: DeleteCommentsByPost :exec
DELETE FROM COMMENTS WHERE post_id = $1
`

func (q *Queries) DeleteCommentsByPost(ctx context.Context, postID string) error {
	_, err := q.db.Exec(ctx, deleteCommentsByPost, postID)
	return err
}

const getCommentsByPost = `-- name: GetCommentsByPost :many
select id, post_id, user_id, content, created_at, updated_at from comments where post_id = $1
`

func (q *Queries) GetCommentsByPost(ctx context.Context, postID string) ([]Comment, error) {
	rows, err := q.db.Query(ctx, getCommentsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsByPosts = `-- name: GetCommentsByPosts :many
WITH RankedComments AS (
    SELECT
        id, post_id, user_id, content, created_at, updated_at,
        ROW_NUMBER() OVER (PARTITION BY post_id ORDER BY created_at DESC) AS rn
    FROM comments
    WHERE post_id = ANY($1::varchar[])
)
select id, post_id, user_id, content, created_at, updated_at, rn from RankedComments where rn <= 10
`

type GetCommentsByPostsRow struct {
	ID        string
	PostID    string
	UserID    string
	Content   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Rn        int64
}

func (q *Queries) GetCommentsByPosts(ctx context.Context, dollar_1 []string) ([]GetCommentsByPostsRow, error) {
	rows, err := q.db.Query(ctx, getCommentsByPosts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByPostsRow
	for rows.Next() {
		var i GetCommentsByPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
