// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        string
	PostID    string
	UserID    string
	Content   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	UserName  string
}

type Post struct {
	ID        string
	CreatedBy string
	Username  string
	Content   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Filepath  pgtype.Text
}

type User struct {
	ID           int32
	UserID       string
	Username     string
	LastLogin    pgtype.Timestamptz
	LastNotified pgtype.Timestamptz
}

type UserFollow struct {
	FollowerID       string
	FollowedID       string
	NotificationType pgtype.Text
	FollowedAt       pgtype.Timestamp
}

type UserSubscription struct {
	UserID       string
	Subscription []byte
	CreatedAt    pgtype.Timestamptz
}
